language: python

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
install:
    - pip install -r requirements-test.txt
jobs:
    include:
        - stage: check mypy
          script: mypy
        - stage: check flake8
          script: flake8
        - stage: check black
          if: env(TRAVIS_PYTHON_VERSION) != "3.5"
          script: black --check --diff --fast .
