__copyright__ = "Copyright (C) 2018 Ryunosuke Seto"
__version__ = "0.1.0"
__license__ = "MIT License"
__author__ = "Seto Ryunosuke"
__author_email__ = "theshootingstar@hotmail.co.jp"
__url__ = "http://github.com/seto-r/mymypy"
